### ISSUE TITLE
syntax error main.py

### ISSUE THREAD

**Issue by Furiousness** [zackmawaldi/YouTube-shorts-generator#14]
![Capture](https://user-images.githubusercontent.com/34078369/187098566-d04e4b88-5144-42d0-a1cf-1e67b2101dba.PNG)

Ive tried to fix anything and restored it back to the 23rd category but nothing seems to be working. Any Idea?

**Comment by zackmawaldi** [comment]
hmm... this works on python3. Are you running python3? You can check via `python --version` in cmd.
You can also try running `main.py` by `python3 main.py` and not `python main.py` in your counsel. Hope that helps!

**Comment by Furiousness** [comment]
I tried that and it says now

 \Downloads\YouTube-shorts-generator-main\YouTube-shorts-generator-main\main.py", line 2, in <module>
    from redvid import Downloader
ModuleNotFoundError: No module named 'redvid'

I do have redvid installed and I tried uninstalling and reinstalling it and that didn't work but its a completely new message.

**Comment by zackmawaldi** [comment]
Maybe there is a python environment mismatch? Other words, redvid installed in the wrong env?
