### ISSUE TITLE
An error occurred in main() on attempt 1: invalid_grant error processing request

### ISSUE THREAD

**Issue by G59Dev** [zackmawaldi/YouTube-shorts-generator#27]
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 1: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 2: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 3: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 4: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 5: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 6: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 7: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 8: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 9: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 10: invalid_grant error processing request
Attempted to upload 10 times with no luck... ending script.

**Comment by akhil3417** [comment]
make sure u have copied your "client_id" correctly , for it will have a "-" in front. 

reddit_login = {
	'client_id': '-yourclientid',
	}
