### ISSUE TITLE
isbug: proces restarts after dowload and encoding

### ISSUE THREAD

**Issue by akhil3417** [zackmawaldi/YouTube-shorts-generator#28]
➜ python main.py
Logging into Reddit...
Log in success! Retrieving post info...
Scraping reddit success! Returning list of info back to main.
Video chosen:
url https://v.redd.it/bkhxvxbfslcb1
title Little man wasn't about to be denied again...
author thejeffroc
Attempting to download reddit video...
>> Connecting...
>> Scraping...
>> Downloading and Re-encoding...
>> Video:
>>>> [██████████████████████████████████████████████████] [6.43/6.43 MB]
>> Audio:
>>>> [██████████████████████████████████████████████████] [0.90/0.90 MB]
>> Done
Download success!
Moviepy - Building video temp_clips/output.mp4.
MoviePy - Writing audio in outputTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video temp_clips/output.mp4

Moviepy - Done !
Moviepy - video ready temp_clips/output.mp4
An error occurred in main() on attempt 1: Expecting value: line 1 column 1 (char 0)
Logging into Reddit...
Log in success! Retrieving post info...

 **Here its re-starts download **
and i have to intervene to stop the process.

**Comment by akhil3417** [comment]
their were some errors in my client_secrets.json 

but a more verbose error message , would be great

**Comment by zackmawaldi** [comment]
I agree, thank you for bringing it up to my attention. I just implemented more verbose error messaging :)
