### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by ibbizaki123** [zackmawaldi/YouTube-shorts-generator#32]
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 2: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 3: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 4: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 5: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 6: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 7: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 8: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 9: invalid_grant error processing request
Logging into Reddit...
Log in success! Retrieving post info...
An error occurred in main() on attempt 10: invalid_grant error processing request
Attempted to upload 10 times with no luck... ending script.

**Comment by casperrr** [comment]
Make sure you have put your info in correctly inside `config.py`. I had this issue because I was using a google account which doesnt have a password so I was unable to login through the api. Make sure u use an account that has a password and not sign up with other services.

**Comment by zackmawaldi** [comment]
Precisely what @casperrr mentioned. I recommend making a separate account. The [README.md](https://github.com/zackmawaldi/YouTube-shorts-generator/blob/main/README.md) has a tutorial linked. Let me know if the issue persists.
