### ISSUE TITLE
An error occurred in main() on attempt 1: 'video_fps'

### ISSUE THREAD

**Issue by ridhoalif** [zackmawaldi/YouTube-shorts-generator#33]
An error occurred in main() on attempt 1: 'video_fps'
I got this error after scrapping from reddit got success

**Comment by ridhoalif** [comment]
I got pass that error, it seems that I got 0mb video and that gives me error like above.
now with correct video I got this error 
An error occurred in main() on attempt 1: Expecting value: line 5 column 23 (char 188)

**Comment by zackmawaldi** [comment]
I was able to reproduce the issue. Reddit changed how their videos are structured. Retry it now, should be OK. Let me know otherwise.
