### ISSUE TITLE
How to install this script?

### ISSUE THREAD

**Issue by srdjan1987** [zackmawaldi/YouTube-shorts-generator#7]
Hi guys, probably is the noobiest question ever, but how do you install this script? When I try installing it via cmd it says

ERROR: git+https://github.com/zackmawaldi/YouTube-shorts-generator.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Thank you

**Comment by iHeka** [comment]
on git bash: git clone "https://github.com/zackmawaldi/YouTube-shorts-generator"
for configure this you need to refeer to the read-me and api's documentations (youtube and reddit)

**Comment by mindbreaker** [comment]
```
pip install redvid
pip install moviepy
pip install scikit-image
pip install apiclient
pip install praw
pip install httplib2
pim install oauth2client
pip install --upgrade google-api-python-client
```
