### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ChiefG** [zackmawaldi/YouTube-shorts-generator#8]

**Comment by zackmawaldi** [comment]
I think if you pip install:

httplib2
apiclient
oauth2client
moviepy
skimage
praw
redvid

and download ffmpeg, everything should be all set. If you already did that, please provide details so I can try to help!

**Comment by Flaam** [comment]
It looks like that skimage is not working anymore, the PIP install prompts to install "scikit-image" instead of skimage
